// <auto-generated />
using GardenApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GardenGuardian.Migrations
{
    [DbContext(typeof(GardenApiContext))]
    [Migration("20240311211210_AddSeedTag")]
    partial class AddSeedTag
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GardenApi.Models.Garden", b =>
                {
                    b.Property<int>("GardenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GardenId"));

                    b.Property<int>("GridQty")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.HasKey("GardenId");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("GardenApi.Models.Grid", b =>
                {
                    b.Property<int>("GridId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GridId"));

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GridId");

                    b.ToTable("Grids");
                });

            modelBuilder.Entity("GardenApi.Models.Seed", b =>
                {
                    b.Property<int>("SeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeedId"));

                    b.Property<string>("DatePlanted")
                        .HasColumnType("text");

                    b.Property<string>("DaysToGerminate")
                        .HasColumnType("text");

                    b.Property<int>("DaysToHarvest")
                        .HasColumnType("integer");

                    b.Property<string>("DepthToSow")
                        .HasColumnType("text");

                    b.Property<string>("Information")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("PlantingDates")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Results")
                        .HasColumnType("text");

                    b.Property<string>("RowSpacing")
                        .HasColumnType("text");

                    b.Property<string>("SeedSpacing")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("Yield")
                        .HasColumnType("integer");

                    b.HasKey("SeedId");

                    b.ToTable("Seeds");

                    b.HasData(
                        new
                        {
                            SeedId = 1,
                            DatePlanted = "2-14-2024",
                            DaysToGerminate = "5-10",
                            DaysToHarvest = 45,
                            DepthToSow = "1/4-1/2 in",
                            Information = "The Hakurei Turnip (a.k.a Tokyo Turnip) variety is usually stark white and has an unmatched crispness and tender sweetness. This turnip is commonly eaten raw which has led to it being given the nickname of 'Salad Turnip'.",
                            Name = "Hakurei Turnip",
                            PhotoUrl = "https://cdn.mos.cms.futurecdn.net/HMr9ceyW7Sc2kuz2S3dNF5.jpg",
                            PlantingDates = "spring, fall, winter",
                            Quantity = 10,
                            Results = "n/a",
                            RowSpacing = "12-24in",
                            SeedSpacing = "2 in",
                            Status = "planted",
                            Type = "vegetable",
                            Yield = 5
                        });
                });

            modelBuilder.Entity("GardenApi.Models.SeedTag", b =>
                {
                    b.Property<int>("SeedTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeedTagId"));

                    b.Property<int>("SeedId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("SeedTagId");

                    b.HasIndex("SeedId");

                    b.HasIndex("TagId");

                    b.ToTable("SeedTags");
                });

            modelBuilder.Entity("GardenApi.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("NameTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("GardenApi.Models.SeedTag", b =>
                {
                    b.HasOne("GardenApi.Models.Seed", "Seed")
                        .WithMany("SeedTags")
                        .HasForeignKey("SeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GardenApi.Models.Tag", "Tag")
                        .WithMany("SeedTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seed");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("GardenApi.Models.Seed", b =>
                {
                    b.Navigation("SeedTags");
                });

            modelBuilder.Entity("GardenApi.Models.Tag", b =>
                {
                    b.Navigation("SeedTags");
                });
#pragma warning restore 612, 618
        }
    }
}
